### ISSUE TITLE
Issue in 0.111.1 LockDevice is deprecated

### ISSUE THREAD

**Issue by RXM307** [gaggle331/home-assistant-kevo#6] opened 2020-06-13 11:51 UTC
2020-06-13 21:37:28 WARNING (MainThread) [homeassistant.components.lock] LockDevice is deprecated, modify KevoDevice to extend LockEntity

My be present in older versions but only got around to installing this....

If I get a chance I'll try to work out what changes are needed but python is not my strength.

**Comment by aLTeReGo-SWI** [comment] 2020-08-16 12:10
Seeing the same thing in 0.114.1

LockDevice is deprecated, modify KevoDevice to extend LockEntity

**Comment by RXM307** [comment] 2020-08-16 22:02
these commits in this pull request "should" fix this issue but I personally haven't tested this yet

https://github.com/gaggle331/home-assistant-kevo/pull/8

**Comment by gaggle331** [comment] 2020-08-16 22:17
I merged that pull request, hopefully the issue is fixed. I don't lose my Kevo locks anymore so I can't test, but I'll try to keep up with merge requests as best I can.

**Comment by RXM307** [comment] 2021-04-07 06:23
Thanks this works.

**Closed as completed** 2021-04-07 06:23 UTC
